name: Automerge
on:
  workflow_call:
  # pull_request:
  #   types:
  #     - labeled
  #     - ready_for_review
  # pull_request_review:
  #   types:
  #     - submitted
  # check_suite:
  #   types:
  #     - completed
jobs:
  automerge:
    name: 🔄 Automerge
    if: github.event_name == 'pull_request' && github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'version')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "version"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "squash"
