name: Automerge
on:
  pull_request:
    types:
      - labeled
    paths:
      - VERSION

jobs:
  check_pr:
    if: github.actor == 'jarvis-ubidata' && github.event.action == 'labeled' && contains(github.event.pull_request.labels.*.name, 'version-env')
    name: "Checks contributors"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v14.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          linesChanged: 1
          filesChanged: 1

  automerge:
    needs: check_pr
    name: 🔄 Automerge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "version"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "squash"
          LOG: "TRACE"
      - name: Feedback
        if: steps.automerge.outputs.merged == 'true'
        run: echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} has been merged"

  get_env_from_label:
    needs: automerge
    name: Get Environment from Label
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.get_env.outputs.env }}
    steps:
      - name: Get Environment from Label
        id: get_env
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const env = labels.find(label => label.startsWith('env-'));
            return { env: env ? env.split('-')[1] : 'DEV' }
      - name: Set Environment
        run: echo "Environment is ${{ steps.get_env.outputs.env }}"

  setup:
    needs: get_env_from_label
    name: Setup
    uses: ./.github/workflows/tag_to_deploy.yml
    with:
      environment: ${{ needs.get_env_from_label.outputs.env }}
    permissions: write-all
    secrets: inherit
