name: Automerge
on:
  pull_request:
    types:
      - opened
    paths:
      - VERSION
  check_suite:
    types:
      - completed

jobs:
  check_pr:
    if: github.actor == 'jarvis-ubidata' && contains(github.event.pull_request.labels.*.name, 'version')
    name: "Checks contributors"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v14.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          linesChanged: 1
          filesChanged: 1

  automerge:
    needs: check_pr
    name: 🔄 Automerge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "version"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_METHOD: "squash"
          LOG: "TRACE"
      - name: Feedback
        if: steps.automerge.outputs.merged == 'true'
        run: echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} has been merged"

  get_env_from_label:
    needs: automerge
    name: Get Environment from Label
    runs-on: ubuntu-latest
    steps:
      - name: Get Environment from Label
        id: get_env
        run: |
          echo "Environment is $environment"

          ## get the environment from the github label that starts with env
          github_label=$(echo $environment | grep -oP 'env-\K\w+')

          ## print the environment
          echo "Environment: $github_label"

          ## set the environment to the github label
          echo "ENVIRONMENT=$github_label" >> $GITHUB_ENV

      - name: Set Environment
        run: echo "Environment is ${{ env.ENVIRONMENT }}"

  setup:
    needs: get_env_from_label
    name: Setup
    uses: ./.github/workflows/tag_to_deploy.yml
    with:
      environment: ${{ needs.get_env_from_label.outputs.env }}
    permissions: write-all
    secrets: inherit
