# name: automerge
# on:
#   pull_request:
#     types:
#       - labeled
#       - ready_for_review
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
# jobs:
# automerge:
#   runs-on: ubuntu-latest
#   permissions:
#     contents: write
#     pull-requests: write
#   steps:
#     - id: automerge
#       name: automerge
#       uses: "pascalgn/automerge-action@v0.16.4"
#       env:
#         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#         MERGE_LABELS: "version"
#         MERGE_REQUIRED_APPROVALS: "0"

# tag_to_deploy:
#   name: "🏷️ Create tag"
#   needs: automerge
#   uses: ./.github/workflows/tag_to_deploy.yml
#   permissions: write-all
#   secrets: inherit
#   with:
#     # TODO: THINK HOW TO PASS THE ENV FROM BUMPING TO TAG_TO_DEPLOY WHEN AUTOMERGE HAPPENS
#     environment: ${{github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'DEV'}}
