name: Bump without PR

on:
  workflow_dispatch:

jobs:
  # checkout code
  # git add a change to the VERSION file
  # git commit the change
  # git push the change
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version
        run: |
          git config --global user.email "thisismefake@ubidata.com"
          git config --global user.name "stanley-ubidatasssssdasfasfs"


          #   print current git user
          echo "Current git user: $(git config user.name)"
          touch new_file.txt
          echo "Hello2" > new_file.txt
          git add new_file.txt
          git commit -m "Add new file"	
          git push
