name: Bump version on PR

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: DEV
        required: true
      patch_version:
        type: number
        default: "-"
        required: false
      min_version:
        type: number
        default: "-"
        required: false
      major_version:
        default: "-"
        type: number
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running tests"
          # print event name, type and action
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Event branch: ${{ github.event.pull_request.base.ref }}"
          echo "Event head branch: ${{ github.event.pull_request.head.ref }}"
          echo "Event merged: ${{ github.event.pull_request.merged }}"
          echo "Event labels: ${{ github.event.pull_request.labels.*.name }}"
          echo "Event inputs: ${{ github.event.inputs.environment }}"
          echo "Event actor: ${{ github.actor }}"

  trigger-check:
    name: 🚦 Trigger check
    if: ${{ github.event_name == 'pull_request' && (github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'version')) || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if version is required based on environment value
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # if version is empty or dash AND envrionement is QA
            if [ "${{ github.event.inputs.environment }}" == "QA" ] && [ "${{ github.event.inputs.min_version }}" == "-" ]; then
              echo "Version is required for QA environment"
              exit 1
            fi
          fi
        shell: bash
  update-version:
    name: 📜 Update version
    permissions:
      contents: write
      pull-requests: write
    needs: trigger-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print actor
        run: |
          echo ${{ github.actor }}
          echo ${{ github.event.pull_request.head.ref }}
        shell: bash

      - name: print hello if actor is not jarvis
        if: ${{ github.actor == 'jarvis-ubidata' }}
        run: echo "Hello"
        shell: bash

      - name: Update version
        id: update_monorepo_version
        run: |
          ## get the current version
          current_version=$(cat VERSION)

          ## print the current version
          echo "Current version: $current_version"

          # Run the shell script and capture its output
          new_version=$(python bump_version.py $current_version ${{ github.event.inputs.major_version }} ${{ github.event.inputs.min_version }} ${{ github.event.inputs.patch_version }})

          # Print the captured output for verification
          echo "Shell script output: $new_version"

          ## print the new version
          echo "$new_version" > VERSION

        shell: bash

      - name: Set environment variable
        env:
          NEW_VERSION: ${{ steps.update_monorepo_version.outputs.new_version }}
        id: set_env_variable
        shell: bash
        run: |
          # Navigate to the apps directory

          # Assign file content to an environment variable
          export NEW_VERSION=$(cat VERSION)

          # Display the environment variable
          echo "New version from environment variable: $NEW_VERSION"

          # Set the environment variable for the next steps GITHUB
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.STANLEY_TOKEN }}
          reviewers: ${{ github.actor }}
          body: |
            This PR updates the version file to ${{ env.NEW_VERSION }}.
            Version update from PR created by ${{ github.actor }} on ${{ github.event.pull_request.head.ref }}.

          commit-message: Update version file through script
          title: "Bump version to ${{ env.NEW_VERSION }}"
          delete-branch: true
          labels: version
          branch: version-${{ env.NEW_VERSION}}
          base: main

  determine_environment_by_trigger:
    name: 🧪 Determine environment
    runs-on: ubuntu-latest
    needs: update-version
    outputs:
      environment: ${{ steps.set_env_variable.outputs.environment }}
    steps:
      - name: Set environment variable
        id: set_env_variable
        run: |
          # If the event is a pull request, env is DEV. Otherwise, it is the input value from the workflow_dispatch.
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "environment=DEV" >> $GITHUB_OUTPUT
          else
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          fi

          # Display the environment variable to verify it
          echo "Environment variable: $environment"
  setup:
    needs: determine_environment_by_trigger
    uses: ./.github/workflows/tag_to_deploy.yml
    with:
      environment: ${{ needs.determine_environment_by_trigger.outputs.environment }}
    permissions: write-all
    secrets: inherit
