name: Bump without PR

on:
  workflow_dispatch:

jobs:
  # checkout code
  # git add a change to the VERSION file
  # git commit the change
  # git push the change
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump version
        run: |
          #   git remote add origin https://${{secrets.STANLEY_TOKEN}}@github.com/stanley-ubidata/pr-playground.git

          #   print current git user
          echo "Current git user: $(git config user.name)"
          touch new_file.txt
          echo "Hello" > new_file.txt
          git add new_file.txt
          git commit -m "Add new file"	
          git push https://${{secrets.STANLEY_TOKEN}}@github.com/stanley-ubidata/pr-playground.git
