name: Bump version on PR

on:
  pull_request:
    types: [closed]
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      enviroment:
        type: environment
        default: DEV
        required: true
      min_version:
        type: number
        default: "-"
        required: false
      major_version:
        default: "-"
        type: number
        required: false

jobs:
  envionment-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if version is required based on environment value
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # if version is empty or dash AND envrionement is QA
            if [ "${{ github.event.inputs.enviroment }}" == "QA" ] && [ "${{ github.event.inputs.min_version }}" == "-" ]; then
              echo "Version is required for QA environment"
              exit 1
            fi
          fi
        shell: bash
  update-version:
    needs: envionment-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print actor
        run: |
          echo ${{ github.actor }}
          echo ${{ github.event.pull_request.head.ref }}
        shell: bash

      - name: print hello if actor is not jarvis
        if: ${{ github.actor == 'jarvis-ubidata' }}
        run: echo "Hello"
        shell: bash

      - name: Update version
        id: update_monorepo_version
        run: |
          ## get the current version
          current_version=$(cat VERSION)

          ## print the current version
          echo "Current version: $current_version"

          # Run the shell script and capture its output
          new_version=$(python bump_version.py $current_version)

          # Print the captured output for verification
          echo "Shell script output: $new_version"

          ## print the new version
          echo "$new_version" > VERSION

        shell: bash

      - name: Set environment variable
        env:
          NEW_VERSION: ${{ steps.update_monorepo_version.outputs.new_version }}
        id: set_env_variable
        shell: bash
        run: |
          # Navigate to the apps directory

          # Assign file content to an environment variable
          export NEW_VERSION=$(cat VERSION)

          # Display the environment variable
          echo "New version from environment variable: $NEW_VERSION"

          # Set the environment variable for the next steps GITHUB
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ github.actor }}
          body: |
            This PR updates the version file to ${{ env.NEW_VERSION }}.
            Version update from PR created by ${{ github.actor }} on ${{ github.event.pull_request.head.ref }}.

          commit-message: Update version file through script
          title: "Bump version to ${{ env.NEW_VERSION }}"
          delete-branch: true
          labels: version
          branch: version-${{ env.NEW_VERSION}}
          base: main
