name: Bump version on PR

on:
  pull_request:
    types: [closed]
    branches:
      -  "main"


jobs:
  update-version:
    
    runs-on: ubuntu-latest
    steps:
      - name: Print actor of the event and of cloned pull request
        run: | 
          echo ${{ github.actor }}
          echo ${{ github.event.pull_request.user.login }}
        shell: bash
      
      - name: print hello if actor is not jarvis
        run: echo "Hello"
        shell: bash

