name: Deploy from Tag

on:
  push:
    tags:
      - "v*"

jobs:
  parse-tag:
    name: 🏷️ Parse Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag-parts.outputs.version }}
      build_number: ${{ steps.tag-parts.outputs.build_number }}
      app: ${{ steps.tag-parts.outputs.app }}
      environment: ${{ steps.tag-parts.outputs.environment }}
    steps:
      # name with emojis
      - name: 🐛 Debug Tag Info
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

      - name: ✂️ Extract tag parts
        id: tag-parts
        run: |
          echo "Starting tag parsing..."

          # Remove 'v' prefix from tag
          TAG_WITHOUT_V=${GITHUB_REF_NAME#v}
          echo "Tag without v: $TAG_WITHOUT_V"

          # Split by '-' and store parts
          IFS='-' read -r VERSION_WITH_BUILD APP ENV <<< "$TAG_WITHOUT_V"
          echo "After splitting:"
          echo "VERSION_WITH_BUILD: $VERSION_WITH_BUILD"
          echo "APP: $APP"
          echo "ENV: $ENV"

          # Extract version without build number (before '+' if it exists)
          VERSION=${VERSION_WITH_BUILD%+*}

          BUILD_NUMBER=""
          if [[ $VERSION_WITH_BUILD == *"+"* ]]; then
            BUILD_NUMBER=${VERSION_WITH_BUILD#*+}
          fi

          # Use set-output syntax as well as the newer syntax
          {
            echo "version=${VERSION}"
            echo "build_number=${BUILD_NUMBER}"
            echo "app=${APP}"
            echo "environment=${ENV}"
          } >> "$GITHUB_OUTPUT"

          # Debug outputs
          echo "Set outputs:"
          echo "version=$VERSION"
          echo "build_number=$BUILD_NUMBER"
          echo "app=$APP"
          echo "environment=$ENV"

          if [ -z "$VERSION" ] || [ -z "$APP" ] || [ -z "$ENV" ]; then
            echo "Invalid tag format. Expected format: v<version>-<app>-<environment>"
            exit 1
          fi

  verification:
    name: 👀 Verification
    runs-on: ubuntu-latest
    needs: parse-tag
    steps:
      - name: Print environment variables
        run: |
          echo "Version: ${{ needs.parse-tag.outputs.version }}"
          echo "Build Number: ${{ needs.parse-tag.outputs.build_number }}"
          echo "App: ${{ needs.parse-tag.outputs.app }}"
          echo "Environment: ${{ needs.parse-tag.outputs.environment }}"
