name: Print PR Labels

on:
  pull_request:
    types:
      [
        opened,
        labeled,
        unlabeled,
        synchronize,
        reopened,
        ready_for_review,
        closed,
      ]

jobs:
  print-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Labels
        id: get-labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            console.log('All PR Labels:');
            pr.labels.forEach(label => {
              console.log(`- ${label.name}`);
            });

            const envLabel = pr.labels.find(label => label.name.startsWith('env'));
            if (envLabel) {
              console.log('\nFound environment label:', envLabel.name);
              // Extract environment value (remove 'env-' prefix)
              const envValue = envLabel.name.replace(/^env-/, '');
              // Set output variable for use in next steps
              core.setOutput('environment', envValue);
              // Set environment variable for current job
              core.exportVariable('DEPLOY_ENV', envValue);
            } else {
              console.log('\nNo environment label found');
              core.setOutput('environment', 'none');
              core.exportVariable('DEPLOY_ENV', 'none');
            }

            const appLabel = pr.labels.find(label => label.name.startsWith('app'));
            if (appLabel) {
              console.log('\nFound app label:', appLabel.name);
              // Extract app value (remove 'app-' prefix)
              const appValue = appLabel.name.replace(/^app-/, '');
              // Set output variable for use in next steps
              core.setOutput('app', appValue);
              // Set environment variable for current job
              core.exportVariable('DEPLOY_APP', appValue);
            } else {
              console.log('\nNo app label found');
              core.setOutput('app', 'none');
              core.exportVariable('DEPLOY_APP', 'none');
            }

      - name: Use Environment Variable
        run: |
          echo "Environment from label: $DEPLOY_ENV"
          echo "This can be used in subsequent steps or jobs"
          echo "App from label: $DEPLOY_APP"
          echo "This can be used in subsequent steps or jobs"
