name: Print PR Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  print-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Labels
        id: get-labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            console.log('All PR Labels:');
            pr.labels.forEach(label => {
              console.log(`- ${label.name}`);
            });

            const envLabel = pr.labels.find(label => label.name.startsWith('env'));
            if (envLabel) {
              console.log('\nFound environment label:');
              console.log(envLabel.name);
            } else {
              console.log('\nNo environment label found');
            }
