name: Run on PR merged to main

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Bump version on PR"]
    types:
      - completed

jobs:
    run_on_pr_merged_to_main:
        runs-on: ubuntu-latest
        steps:
        - name: Print hello
          run: | 
            echo "Hello from after bump version on PR"
    # Call Multi Jobs Action
    # uses: ./.github/workflows/multi-jobs-action
    multi_jobs_action:
      needs: run_on_pr_merged_to_main
      uses: ./.github/workflows/on_workflows_run.yml
      permissions: write-all
      with:
        flavor: 'qa'
        platform: 'both'

    