name: Run on specific branch

on:
  push:
    branches-ignore: 
      - 'main'     
      - 'version/**' 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: echo "Running tests..."  # Replace with your actual test command