name: Tag and Deploy to QA

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_tag_if_label_version:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version') }}
    runs-on: ubuntu-latest
    steps:
      - name: Create tag mock
        run: |
          echo "Creating tag v${{ env.NEW_VERSION }}"   
          echo "PR by ${{ github.actor }} from ${{ github.event.pull_request.head.ref }} to ${{ github.event.pull_request.base.ref }}"

  create_tag_if_branch_starts_with_version:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'version') }}
    runs-on: ubuntu-latest
    steps:
      - name: Create tag mock
        run: echo "Creating tag v${{ env.NEW_VERSION }}"

  deploy_to_qa:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'version') }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions: write-all
