name: Tag and Deploy to QA

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  create_tag:
    permissions: write-all
    name: 🏷️ Create/Update tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get and store the new version
        env:
          NEW_VERSION: ${{ steps.update_monorepo_version.outputs.new_version }}
        id: set_env_variable
        shell: bash
        run: |
          # Navigate to the apps directory

          # Assign file content to an environment variable
          export NEW_VERSION=$(cat VERSION)

          # Display the environment variable
          echo "New version from environment variable: $NEW_VERSION"

          # Set the environment variable for the next steps GITHUB
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          # Display the environment variable to verify it
          echo "Environment variable input: ${{ inputs.environment }}"

      - name: 🏷️ Create/update tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.STANLEY_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const newTag = 'v${{ env.NEW_VERSION }}-${{ inputs.environment }}';
            const sha = context.sha;

            try {
              await github.rest.git.createRef({
                owner,
                repo,
                ref: `refs/tags/${newTag}`,
                sha
              });
              console.log(`Successfully created tag ${newTag}`);
            } catch (error) {
              if (error.status === 422) { 
                console.log(`Tag ${newTag} already exists. Updating it.`);
                // If the tag already exists, update it
                await github.rest.git.updateRef({
                  owner,
                  repo,
                  ref: `tags/${newTag}`,
                  sha,
                  force: true
                });
                console.log(`Successfully updated tag ${newTag}`);
              } else {
                // If it's any other error, well.. good luck with that. throw it.
                throw error;
              }
            }

  deploy_to_qa:
    name: 🚀 Deploy
    needs: create_tag
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions: write-all
